services:
  app:
    image: toladev1/ams_app:latest
    container_name: ams_app
    restart: always
    volumes:
      - ./.env:/var/www/.env
      - storage_data:/var/www/storage
      - public_data:/var/www/public
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_net

  nginx:
    image: nginx:alpine
    container_name: ams_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/public
      - public_data:/var/www/public
      - storage_data:/var/www/storage
    depends_on:
      - app
    networks:
      - laravel_net

  db:
    image: mysql:8.0
    container_name: asset_management_db
    restart: always
    environment:
      MYSQL_DATABASE: asset_management_db
      MYSQL_USER: asset_management_user
      MYSQL_PASSWORD: asset_management_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_pass"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  laravel_net:
    driver: bridge

volumes:
  dbdata:
  storage_data:
  public_data: