server {
    listen 80;
    server_name _;
    root /var/www/public;
    index index.php index.html;

    location ~* \.(jpg|jpeg|png|gif|css|js|ico|svg|woff|woff2|ttf|map)$ {
        try_files $uri =404;
        expires 30d;
        access_log off;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\. {
        deny all;
    }
}